name: Daily Run NodeJS Script
on:
  push:
    branches:
      - test
  schedule:
    - cron: '30 7 * * *'

jobs:
  Run-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run NodeJS Script
        run: node main.js

      - name: Commit files
        run: |
          git config --local user.email "yangyata@qq.com"
          git config --local user.name "yangyata"
          git pull
          git status
          git add ./
          git commit -m "feat: daily run nodejs script"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: ${{ env.GITHUB_BASE_BRANCH }}
