name: Daily Run NodeJS Script
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Run-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Run Main NodeJS Script
        run: node ./src/index.js

      - name: Run SendMail NodeJS Script
        run: |
          echo github.event.schedule ${{ github.event.schedule }}
          node ./src/sendMail.js email=${{ secrets.EMAIL_ADDRESS }} email_pass=${{ secrets.EMAIL_PASS }} email_to=${{ secrets.EMAIL_TO }}

      - name: Commit files
        run: |
          git config --local user.email "${{ secrets.MY_GIT_EMAIL }}"
          git config --local user.name "${{ secrets.MY_GIT_USERNAME }}"
          git pull
          git status
          git add ./
          git commit -m "feat: daily run script update wallpaper"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
